version: "0.2"
words:
  - adksetup
  - aily
  - amdtemp
  - AUTOCERT
  - autofitter
  - AUTOUPDATE
  - badblocks
  - bbwe
  - bindkey
  - browserslist
  - Bubuntu
  - clsx
  - CNAME
  - configd
  - CONFIGUPDATE
  - coretemp
  - Cortana
  - dchp
  - ddclient
  - ddns
  - Diffie
  - dism
  - distro
  - donwloaded
  - DWORD
  - dyndns
  - easyops
  - EEST
  - esphome
  - fontconfig
  - freetype
  - gdbm
  - GENSUDO
  - geoip
  - geoipupdate
  - geolocation
  - ghostscript
  - giflib
  - graphviz
  - groff
  - Hairpinning
  - hiadaptive
  - HKCU
  - HKLM
  - hotspot
  - INET
  - INSTALLDIR
  - Intellimenus
  - jbigkit
  - Leay
  - libfontenc
  - libgd
  - libmaxminddb
  - libpaper
  - libsodium
  - libzmq
  - localdomain
  - LOGPATH
  - lywsd03mmc
  - macaddress
  - maintainership
  - maxmind
  - maxminddb
  - Memstick
  - mkdir
  - mkfontscale
  - msiexec
  - nasip
  - ndpi
  - netpbm
  - Nextcloud
  - ntop
  - ntopng
  - ntuser
  - ooobe
  - openpgm
  - pfsense
  - powersave
  - ppem
  - proto
  - protobuf
  - publickey
  - ronivay
  - SATA
  - Segura
  - SELFUPGRADE
  - smartctl
  - smartd
  - smartmontools
  - ssid
  - STANDBYIDLE
  - Sticktable
  - Systray
  - thermalzone
  - thisisa
  - timeseries
  - TOTP
  - traefik
  - truenas
  - truetype
  - tsdb
  - uchardet
  - umounting
  - unattend
  - untunneled
  - USESUDO
  - verdana
  - VIDEOIDLE
  - vnstat
  - webfonts
  - webp
  - wekyb
  - wemos
  - wrover
  - xiaomi
  - xorg
  - XOUSER
  - yourdomain
  - YOURPASSWORD
  - Zabbix
  - zstd
